### VALUES YOU SHOULD CHANGE ###

# GENERAL SITE SETTINGS
# title: This will be displayed as the website's name in your browser tab.
title: Chris Moroney
# description: This will be meta HTML tag content. This can be ignored.
description: My Jekyll Portfolio
# baseurl: The subpath of your site
# > set this to "", if you renamed the repository to <user>.github.io
baseurl: ""

# LANDING PAGE
# username: This will displayed on the landing page as your name.
username: Chris Moroney
# typing_text: This will be typed before 'scroll down for more'.
# > set this to your job title, e.g. Fullstack Developer
typing_text: Software Engineer
# email: Your E-Mail address for the email button.
email: christopher.moroney1@gmail.com
# For every social button you want to display, set your username or userid
# If you do not use one of the following websites, then leave it empty
# > twitter_username:
github_username: chrismoroney
codepen_username: chrismoroney
dev_username: 
linkedin_username: christopher-moroney-36baa11a3/
twitter_username: chrismoroney39

# ABOUT ME SECTION
# show_aboutme_card:
# > setting this to true, will display the About Me section
# > setting this to false, will omit the About Me section
show_aboutme_card: true
# about_me_title: The will be displayed as the title in the About Me section
about_me_title: About Me
# about_me_description: This will be displayed under the title.
about_me_description: <h1> Hello! &#128075;</h1> I'm <b>Chris Moroney</b>, a software engineer passionate about creating intelligent systems that are robust, scalable, and deeply human-centered. My journey started with a formal education in computer science—earning my B.S. from Seattle Pacific University—where I became fascinated by how software and AI could be used to drive meaningful impact in the real world.<br><br>
  During my time in school, I pursued opportunities beyond the classroom, earning the <b>AI Professional Certificate</b> from Deeplearning.ai and a <b>TinyML Certificate</b> from HarvardX. That curiosity and drive led to an internship at <b>Deeplearning.ai</b>, where I developed TensorFlow-based models for medical imaging and deployed machine learning workflows to the cloud. It was my first hands-on exposure to applied AI and gave me a strong foundation in model development and deployment.<br><br>
  I then joined <b>Cambia Health Solutions</b>, where I worked on validating medical data pipelines, translating legacy SAS scripts into Python, and optimizing internal tools to turn grouped medical data into actionable insights. This early-career experience sharpened my data engineering skills and taught me how to work effectively in production environments.<br><br>
  At <b>Milliman</b>, I took on larger responsibilities—engineering full-stack applications in .NET and React, managing backend services that handled over a million API calls per month, and building large-scale data pipelines processing more than 200TB of data monthly. I also deployed infrastructure on Azure using Terraform and led CI/CD automation efforts that dramatically reduced deployment time and errors. During this time, I deepened my AI expertise by earning the <b>TensorFlow Developer Certificate</b>.<br><br>
  Most recently, at <b>Cisco</b>, I’ve focused on the cutting edge of <b>Generative AI</b> and <b>agentic workflows</b>. I designed systems powered by large language models that automate job search tasks—from resume matching to personalized cover letter generation—while also contributing to the creation of educational curriculum in this space. I’ve applied prompt engineering and LLM APIs in real-world tools that blend intelligence with usability.<br><br>
  My core stack includes Python, .NET, React, TensorFlow, Azure, and Terraform, but I'm always learning and evolving. Whether it's architecting infrastructure, fine-tuning an LLM, or mentoring others through curriculum, I aim to bridge software engineering with the forward edge of AI innovation.<br><br>
  You can explore my <a class="highlight-link" href="https://github.com/chrismoroney" target="_blank" rel="noreferrer">GitHub</a> to see examples of my work, and view my full <b>resume</b> <a class="highlight-link" href="/assets/Chris Moroney Resume 202506.pdf" target="_blank" rel="noreferrer">here</a>.
# SKILLS SECTION
# show_skills_card:
# > setting this to true, will display the Skills section
# > setting this to false, will omit the Skills section
show_skills_card: true
# about_me_title: The will be displayed as the title in the Skills section
skills_title: Skills

# TIMELINE SECTION
# show_timeline_card:
# > setting this to true, will display the Timeline section
# > setting this to false, will omit the Timeline section
show_timeline_card: true
# timeline_title: The will be displayed as the title in the Timeline section
timeline_title: Education & Experience
# cv_download_link: The link where you host your cv.
# > e.g. you share your cv on your dropbox, then add the dropbox link here
cv_download_link: /assets/Chris Moroney Resume 202506.pdf

# PROJECTS SECTION
# show_projects_card:
# > setting this to true, will display the Projects section
# > setting this to false, will omit the Projects section
show_projects_card: true
# show_projects:
# > setting this to true, will display your listed projects in _data/projects.yml
# > setting this to false, will omit your listed projects
show_projects: true
# projects_title: The will be displayed as the title of your projects
projects_title: Projects
# show_os_projects:
# > setting this to true, will display your public projects on github
# > setting this to false, will omit your public projects on github
show_os_projects: true
# os_projects_title: The will be displayed as the title of your open source projects
os_projects_title: Open Source Projects

# CONTACT SECTION
# show_contact_card:
# > setting this to true, will display the Contact section
# > setting this to false, will omit the Contact section
show_contact_card: true
# contact_title: The will be displayed as the title in the Contact section
contact_title: Contact
# contact_description: This will be displayed under the title.
contact_description: Feel free to contact me with any of these methods below!

# GITHUB-METADATA
# Set this to your forked repository
# > e.g. <user>/<user>.github.io
repository: chrismoroney.chrismoroney.github.io
projects:
  # sortby:
  # > set this to pushed, if you want to sort your github repositories by time.
  # > set this to stars, if you want to sort your github repositories by stars.
  sort_by: pushed
  exclude:
    # archived:
    # > setting this to true, will exclude archived repositories
    # > setting this to false, will also display archived repositories
    archived: true
    # forks:
    # > setting this to true, will exclude forked repositories
    # > setting this to false, will also display forked repositories
    forks: true
    # projects: A list of the repository names you want to exclude from the listing.
    projects:
    # - repo1-to-be-excluded
    # - repo2-to-be-excluded
    - chrismoroney.github.io
    - Seattle-Pacific-University-CSC-3430
    - Seattle-Pacific-University-MAT-3380
    - mameon
    - chrismoroney
    - Seattle-Pacific-University-CSC-4151-4152
    - spu-hackathon
    - Seattle-Pacific-University-CSC-4210
    - Seattle-Pacific-University-CSC-3221
    - Seattle-Pacific-University-CSC-3310
    - Seattle-Pacific-University-CSC-3760
    - Seattle-Pacific-University-CSC-3220
    - Seattle-Pacific-University-EE-1210
    - Bellevue-College-CS-210
    - Bellevue-College-CS-211
    - Bellevue-College-CS-212
    - Bellevue-College-BUSIT-103

# GOOGLE-ANALYTICS
# Set the id, if you want to track your website with Google Analytics
# > set this to "", if you do not want to track with Google Analytics
google-analytics:
  id: "UA-200631653-1"

### END OF VALUES YOU SHOULD CHANGE ###

plugins:
  - "jekyll-github-metadata"

exclude:
  [
    "_assets",
    "Gemfile",
    "Gemfile.lock",
    "gulpfile.js",
    "node_modules",
    "package.json",
  ]
